const meals=[
    {id:1 ,name:"nameOne", type:"typeOne"},
    {id:2 ,name:"nameOne", type:"typeOne"},
    {id:3 ,name:"nameOne", type:"typeOne"},
    {id: 4,name:"nameOne", type:"typeOne"},
    {id:5 ,name:"nameOne", type:"typeOne"},
    {id:6 ,name:"nameOne", type:"typeOne"},
    {id:7 ,name:"nameOne", type:"typeOne"},
    {id:8 ,name:"nameOne", type:"typeOne"},
    {id:9 ,name:"nameOne", type:"typeOne"},
    {id:10 ,name:"nameOne", type:"typeOne"},
    {id:11 ,name:"nameOne", type:"typeOne"},
    {id:12 ,name:"nameOne", type:"typeOne"},
    {id:13 ,name:"nameOne", type:"typeOne"},
    {id:14 ,name:"nameOne", type:"typeOne"},
]