'Grilled Chicken Salad'
'Veggie Stir-Fry with Tofu'
'Baked Salmon with Asparagus'
'Quinoa and Black Bean Salad'
'Spinach and Feta Stuffed Chicken Breast'
'Zucchini Noodles with Marinara Sauce'
'Turkey Lettuce Wraps'
'Cauliflower Rice Sushi Rolls'
'Grilled Shrimp and Vegetable Skewers'
'Greek Yogurt with Berries and Honey'
'Egg White Omelette with Spinach and Mushrooms'
'Lentil Soup'
'Cabbage Rolls'
'Roasted Brussels Sprouts with Balsamic Glaze'
'Broiled Tilapia with Lemon and Herbs'
'Spaghetti Squash with Tomato Basil Sauce'
'Chicken and Vegetable Kebabs'
'Veggie and Hummus Wrap'
'Cottage Cheese with Pineapple'
'Mixed Green Salad with Grilled Shrimp'
'Tomato Basil Soup'
'Baked Cod with Steamed Broccoli'
'Mushroom and Spinach Quiche'
'Black Bean and Corn Salad'
'Grilled Turkey Burger (lettuce bun)'
'Butternut Squash Soup'
'Chia Seed Pudding'
'Stuffed Bell Peppers with Ground Turkey'
'Broccoli and Cheese Stuffed Chicken'
'Strawberry Spinach Salad with Light Vinaigrette'